FIND_PATH(ADLMIDI_INCLUDE_DIR adlmidi.h
	PATHS $ENV{ADLMIDDIR}/include
)

MESSAGE(STATUS "ADLMIDI_INCLUDE_DIR = ${ADLMIDI_INCLUDE_DIR}")

FIND_LIBRARY(ADLMIDI_LIBRARY NAMES ADLMIDI
	PATHS $ENV{ADLMIDDIR}/lib
)

MESSAGE(STATUS "ADLMIDI_LIBRARY = ${ADLMIDI_LIBRARY}")

# handle the QUIETLY and REQUIRED arguments and set ADLMIDI_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ADLMIDI DEFAULT_MSG ADLMIDI_LIBRARY ADLMIDI_INCLUDE_DIR)

IF(ADLMIDI_FOUND)
  SET(ADLMIDI_LIBRARIES ${ADLMIDI_LIBRARY})
ELSE(ADLMIDI_FOUND)
  SET(ADLMIDI_LIBRARIES)
ENDIF(ADLMIDI_FOUND)

MARK_AS_ADVANCED(ADLMIDI_LIBRARY ADLMIDI_INCLUDE_DIR)
